version: '3.1'
services:
  web:
    container_name: demo_nakul
    image: demo_nakul
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    container_name: sample_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jiiiivan
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    ports:
      - "5433:5433"